apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
spec:
  replicas: 5 # Number of replicas that will be created for this deployment
  selector:
    matchLabels:
      app: angular-web
  template:
    metadata:
      labels:
        app: angular-web
    spec:
      containers:
        - name: angular-web
          image: mathieudielna/angular-web:latest
          ports:
            - containerPort: 80

