apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular-web
spec:
  replicas: 5 # Nombre de réplicas pour ce déploiement
  selector:
    matchLabels:
      app: angular-web
  template:
    metadata:
      labels:
        app: angular-web
    spec:
      containers:
        - name: angular-web
          image: mathieudielna/angular-web:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service.default.svc.cluster.local"  # URL du backend
