apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  # clusterIP: None  # Assure que le service est headless
  selector:
    app: mongo
