apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: default
type: Opaque
data:
  mongodb-root-username: cm9vdA==   # Base64 encoded 'root'
  mongodb-root-password: cm9vdA==   # Base64 encoded 'root'
  mongodb-database: ZmFpcl9wYXk=    # Base64 encoded 'fair_pay'
