apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-init-scripts
  namespace: default
data:
  init.js: |
    db = db.getSiblingDB('fair_pay');
    db.createUser({
      user: 'root',
      pwd: 'root',
      roles: [{ role: 'readWrite', db: 'fair_pay' }]
    });
