apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
  namespace: default
data:
  mongosecret: bXktc2VjcmV0LXNlY3JldA==  # Base64 encoded 'my-secret-secret'
type: Opaque
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  labels:
    app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  # clusterIP: None  # Assure que le service est headless
  selector:
    app: mongo

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongod
  labels:
    app: mongo
spec:
  serviceName: mongodb-service
  replicas: 3
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
        role: mongodb
        replicaset: MainRepSet
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: replicaset
                  operator: In
                  values:
                  - MainRepSet
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 10
      containers:
      - name: mongod-container
        image: mongo:4.4
        imagePullPolicy: IfNotPresent
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
        - name: MONGO_INITDB_DATABASE
          value: "fair_pay"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath

